updates is-svg to 4.3.0; associated dependency updates
dxw/affordable-housing-monitoring pull request #223
Opened 2022-01-05 16:32 UTC by shuldt

2022-01-05 17:06 UTC, erbridge commented
You might want to look at this instead of putting things in the dependencies list: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

2022-01-06 09:05 UTC, shuldt commented
> You might want to look at this instead of putting things in the dependencies list: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

yup this looks very sensible, i'll try it thank you

2022-01-06 15:17 UTC, shuldt commented
/rebase

2022-01-06 16:08 UTC, erbridge requested changes
I'd be happy to chat quickly about what I think needs to change if helpful.

2022-01-06 16:08 UTC, erbridge commented on package.json
> +    "postcss-svgo": "4.0.3"
I'd suggest we don't want the dependencies added. They're not direct dependencies and adding them here makes them look like they are. That's what the resolutions are for - to resolve indirect dependencies.

2022-01-06 16:09 UTC, erbridge commented on Gemfile.lock
> +  x86_64-linux
Are supposed to have linux twice?

2022-01-06 16:42 UTC, erbridge approved these changes

2022-01-06 16:43 UTC, merged